### ISSUE TITLE
Creating All the GUIs

### ISSUE THREAD

**Issue by JakeBlack2003** [bchen203/CargoCo#15]
There will be several GUIs that we need to implement:

**Launch/Start GUI:**
- two buttons for operation: load/offload, balance
- after any option is selected, a pop up window will appear asking for a manifest to be inputted
- once the manifest is given, the next screen will be either the **Load/Offload GUI** or **Balance GUI**
- [Sample Image of Launch/Start GUI](https://cdn.discordapp.com/attachments/1289818564903309333/1307547199160451083/image.png?ex=673ab3b9&is=67396239&hm=dd810668e4b8f91006d5c9b1bf1c56e1558c6abfd27e152dbd8e3db538417a15&)
- [Sample Image of Uploading Manifest](https://cdn.discordapp.com/attachments/1289818564903309333/1307547325601943622/image.png?ex=673ab3d7&is=67396257&hm=8d7e5d9aa28ba5aa34ad87f841762052cadb516f6ed09301f54578b5d52aee12&)

**Load/Offload GUI:**
- a 2D grid representing the manifest is displayed
- container names in the 2D grid will be be cut off after some number of characters (the exact value is not determined yet)
- a hover mouse feature that displays the full name of a container in the 2D grid
- the operator can click on containers in the 2D grid to remove/offload them (these containers will be highlighted in red), clicking the container again will remove it from the offload
- a load button that will create a pop up window asking the operator to enter the name of the container
- a pending loads dropdown or button that displays all of the container names that will be loaded onto the ship
- a pending offloads dropdown or button that displays all of the container names that will be offloaded from the ship
- containers can be directly removed from the pending loads and (maybe) the pending offloads list by clicking a delete icon to the right of the container name (like a red 'x' or something)
- a "GO" button that, when clicked, calculates the solution and changes the screen to the **Instructions GUI**
- [Sample Image of Pending Loads](https://cdn.discordapp.com/attachments/1289818564903309333/1307081372057468948/image.png?ex=673a5363&is=673901e3&hm=57ece2c1c5b27e8d622013827dc7a04085702c32582246f1b3fec0a5d657b259&)
- [Sample Image of Load Button Usage](https://cdn.discordapp.com/attachments/1289818564903309333/1307547525258940416/image.png?ex=673ab407&is=67396287&hm=748809c1179d67544ce82476f09825578a426453c5578d71f7b5a42a428373c5&)

**Balance GUI:**
- immediately advance to **Instructions GUI** (there is no special GUI for the balance solution)

**Instructions GUI:**
- the top of GUI displays the current move number out of a total number of moves and an ETA (in minutes) for how long the entire set of instructions will take (can discuss whether we need this ETA or not)
- under that is the instruction (in text form) to be performed by the operator
- under that is the instruction (in image form) to be performed by the operator, featuring a before and after state of the ship's 2D grid (buffer will need to be added too) via images
- under that is the ETA (in minutes) for how long the current move will take
- to the right of the ETA is a Next button that will advance to the next move
- [Sample Image of Load/Offload Operation](https://cdn.discordapp.com/attachments/1289818564903309333/1307546999452860416/IMG_0154.png?ex=673ab389&is=67396209&hm=072bc9b00a95b63ad54b74fff27e0d09bb7c212f3811f2a12dd0fe08d7c14331&)
- [Sample Image of Balance Operation](https://cdn.discordapp.com/attachments/1289818564903309333/1307546999830351922/image1.jpg?ex=673ab389&is=67396209&hm=3eba8b9e917611ad449931cbeff227245af109b195cb634f2b6be1bb109231b6&)

**Other:**
- error pop up windows
- user input pop up windows
- always-persistent toolbar at the top of the program that allows the operator to:
- sign in/shut down (a user input pop up window for sign in, a confirmation message pop up window for shut down)
- add custom notes to the log (a user input pop up window)
- [Sample Image of Error Pop Up Window](https://cdn.discordapp.com/attachments/1289818564903309333/1307547619681370214/image.png?ex=673ab41d&is=6739629d&hm=365c14b8647b1b365dd22aefc06eb959fa63aacb426ffcc0cd23ffcc581234ed&)
- [Sample Image of Toolbar with the Sign In/Shut Down and Custom Note to Log Features](https://cdn.discordapp.com/attachments/1289818564903309333/1307547736844931102/image.png?ex=673ab439&is=673962b9&hm=955f72665087ca339e88710a6716e681c2210acc428aed2bdd225c81edff6851&)

**Comment by EvergreenQueen** [comment]
Y'all. This is huge. Maybe consider breaking it down a bit??
